// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

namespace MvcMovie.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TortugaLiebre.Models.Clasificatorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Apostadores")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarrera")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ganador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ganancias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumCarrera")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clasificatorias");
                });
#pragma warning restore 612, 618
        }
    }
}
